server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://10.0.2.115:3100/loki/api/v1/push

scrape_configs:
- job_name: switches
  static_configs:
  - targets:
      - localhost
    labels:
      job: ciscolog
      __path__: /var/log/cisco/*log
  pipeline_stages:
  - match:
      selector: '{job="ciscolog"}'
      stages:
      - regex:
          expression: "^(?P<datetime>\\w+\\s+\\d{2}\\s+\\d{2}:\\d{2}:\\d{2})\\s+(?P<hostname>[a-z0-9.-]+)\\s(?P<message>.*)$"
      - labels:
          hostname:
#          datetime:
#          message:
- job_name: system
  static_configs:
  - targets:
    - localhost
    labels:
       job: varlogs
       __path__: /var/log/*log


